[build]
  base = "exampleSite"
  command = "hugo --gc --themesDir ../.. -b $URL"
  publish = "exampleSite/public"

[build.environment]
  HUGO_THEME = "repo"

[context.deploy-preview]
  command = "hugo --gc --themesDir ../.. -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --themesDir ../.. -b $DEPLOY_PRIME_URL"
